#!/usr/bin/env python3
"""Generate FE Unicode case tables from the pinned StringZilla tables."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "be/src/thirdparty/stringzilla/utf8_case/tables.h"
TARGET = ROOT / "fe/fe-core/src/main/java/com/starrocks/common/util/UnicodeCaseData.java"
license = (ROOT / "fe/fe-core/src/main/java/com/starrocks/common/util/UnicodeCase.java").read_text().split("package ")[0]
text = SOURCE.read_text()
lines = [license + "package com.starrocks.common.util;\n", "// Generated by build-support/generate_unicode_case.py. Unicode 17.0.0.",
         "// Mapping data license: be/src/thirdparty/stringzilla/utf8_case/UNICODE-LICENSE.txt.",
         "final class UnicodeCaseData {", "    private UnicodeCaseData() {", "    }"]
for name, source in [("LOWER", "lower_mappings"), ("UPPER", "upper_mappings"),
                     ("CASED", "cased_ranges"), ("IGNORABLE", "case_ignorable_ranges")]:
    body = re.search(r"sz_unicode_" + source + r"_\[\] = \{(.*?)\n\};", text, re.S).group(1)
    values = re.findall(r"0x[0-9A-Fa-f]+|-?\d+", body)
    stride = 7 if name in ("LOWER", "UPPER") else 2
    assert len(values) % stride == 0
    lines.append("    static final int[] " + name + " = {")
    for i in range(0, len(values), stride):
        lines.append("            " + ", ".join(values[i:i + stride]) + ",")
    lines.append("    };")
lines.append("}\n")
TARGET.write_text("\n".join(lines))
