// Copyright 2021-present StarRocks, Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package com.starrocks.sql.parser;

// Token types and the keyword and operator tables of UnifiedBatchedLexer come from the generated lexer,
// so a grammar change does not leave stale token numbers here.
final class FrozenTokenCatalog {
    private FrozenTokenCatalog() {}

    static final int EOF = -1;
    static final int MAX_LEXER_TOKEN_TYPE = StarRocksLexer.VOCABULARY.getMaxTokenType();
    static final int MAX_TOKEN_TYPE = StarRocksParser.VOCABULARY.getMaxTokenType();
    static final int T_0 = StarRocksLexer.T__0;
    static final int T_1 = StarRocksLexer.T__1;
    static final int T_2 = StarRocksLexer.T__2;
    static final int T_3 = StarRocksLexer.T__3;
    static final int T_4 = StarRocksLexer.T__4;
    static final int T_5 = StarRocksLexer.T__5;
    static final int T_6 = StarRocksLexer.T__6;
    static final int T_7 = StarRocksLexer.T__7;
    static final int T_8 = StarRocksLexer.T__8;
    static final int T_9 = StarRocksLexer.T__9;
    static final int ACCESS = StarRocksLexer.ACCESS;
    static final int ACTIVE = StarRocksLexer.ACTIVE;
    static final int ADD = StarRocksLexer.ADD;
    static final int ADMIN = StarRocksLexer.ADMIN;
    static final int ADVISOR = StarRocksLexer.ADVISOR;
    static final int AFTER = StarRocksLexer.AFTER;
    static final int AGGREGATE = StarRocksLexer.AGGREGATE;
    static final int ALL = StarRocksLexer.ALL;
    static final int ALTER = StarRocksLexer.ALTER;
    static final int ANALYZE = StarRocksLexer.ANALYZE;
    static final int AND = StarRocksLexer.AND;
    static final int ANTI = StarRocksLexer.ANTI;
    static final int APPLY = StarRocksLexer.APPLY;
    static final int ARRAY = StarRocksLexer.ARRAY;
    static final int ARRAY_AGG = StarRocksLexer.ARRAY_AGG;
    static final int ARRAY_AGG_DISTINCT = StarRocksLexer.ARRAY_AGG_DISTINCT;
    static final int AS = StarRocksLexer.AS;
    static final int ASC = StarRocksLexer.ASC;
    static final int ASOF = StarRocksLexer.ASOF;
    static final int ASYNC = StarRocksLexer.ASYNC;
    static final int ASSERT_ROWS = StarRocksLexer.ASSERT_ROWS;
    static final int AUTHORS = StarRocksLexer.AUTHORS;
    static final int AUTHENTICATION = StarRocksLexer.AUTHENTICATION;
    static final int AUTOMATED = StarRocksLexer.AUTOMATED;
    static final int AUTO_INCREMENT = StarRocksLexer.AUTO_INCREMENT;
    static final int AVG = StarRocksLexer.AVG;
    static final int AWARE = StarRocksLexer.AWARE;
    static final int BACKEND = StarRocksLexer.BACKEND;
    static final int BACKENDS = StarRocksLexer.BACKENDS;
    static final int BACKUP = StarRocksLexer.BACKUP;
    static final int BASE = StarRocksLexer.BASE;
    static final int BASELINE = StarRocksLexer.BASELINE;
    static final int BEGIN = StarRocksLexer.BEGIN;
    static final int BETWEEN = StarRocksLexer.BETWEEN;
    static final int BIGINT = StarRocksLexer.BIGINT;
    static final int BINARY = StarRocksLexer.BINARY;
    static final int BITMAP = StarRocksLexer.BITMAP;
    static final int BITMAP_UNION = StarRocksLexer.BITMAP_UNION;
    static final int BLACKHOLE = StarRocksLexer.BLACKHOLE;
    static final int BLACKLIST = StarRocksLexer.BLACKLIST;
    static final int BODY = StarRocksLexer.BODY;
    static final int BOOLEAN = StarRocksLexer.BOOLEAN;
    static final int BOTH = StarRocksLexer.BOTH;
    static final int BRANCH = StarRocksLexer.BRANCH;
    static final int BROKER = StarRocksLexer.BROKER;
    static final int BUCKETS = StarRocksLexer.BUCKETS;
    static final int BUILTIN = StarRocksLexer.BUILTIN;
    static final int BY = StarRocksLexer.BY;
    static final int CACHE = StarRocksLexer.CACHE;
    static final int CALL = StarRocksLexer.CALL;
    static final int CANCEL = StarRocksLexer.CANCEL;
    static final int CASE = StarRocksLexer.CASE;
    static final int CAST = StarRocksLexer.CAST;
    static final int CATALOG = StarRocksLexer.CATALOG;
    static final int CATALOGS = StarRocksLexer.CATALOGS;
    static final int CEIL = StarRocksLexer.CEIL;
    static final int CHAIN = StarRocksLexer.CHAIN;
    static final int CHAR = StarRocksLexer.CHAR;
    static final int CHARACTER = StarRocksLexer.CHARACTER;
    static final int CHARSET = StarRocksLexer.CHARSET;
    static final int CHECK = StarRocksLexer.CHECK;
    static final int CLEAN = StarRocksLexer.CLEAN;
    static final int CLEAR = StarRocksLexer.CLEAR;
    static final int CLUSTER = StarRocksLexer.CLUSTER;
    static final int CLUSTERS = StarRocksLexer.CLUSTERS;
    static final int CNGROUP = StarRocksLexer.CNGROUP;
    static final int CNGROUPS = StarRocksLexer.CNGROUPS;
    static final int COLLATE = StarRocksLexer.COLLATE;
    static final int COLLATION = StarRocksLexer.COLLATION;
    static final int COLUMN = StarRocksLexer.COLUMN;
    static final int COLUMNS = StarRocksLexer.COLUMNS;
    static final int COMMENT = StarRocksLexer.COMMENT;
    static final int COMMIT = StarRocksLexer.COMMIT;
    static final int COMMITTED = StarRocksLexer.COMMITTED;
    static final int COMPACT = StarRocksLexer.COMPACT;
    static final int COMPACTION = StarRocksLexer.COMPACTION;
    static final int COMPUTE = StarRocksLexer.COMPUTE;
    static final int CONFIG = StarRocksLexer.CONFIG;
    static final int CONNECTION = StarRocksLexer.CONNECTION;
    static final int CONNECTIONS = StarRocksLexer.CONNECTIONS;
    static final int CONSISTENT = StarRocksLexer.CONSISTENT;
    static final int CONVERT = StarRocksLexer.CONVERT;
    static final int COSTS = StarRocksLexer.COSTS;
    static final int COUNT = StarRocksLexer.COUNT;
    static final int CREATE = StarRocksLexer.CREATE;
    static final int CROSS = StarRocksLexer.CROSS;
    static final int CUBE = StarRocksLexer.CUBE;
    static final int CUME_DIST = StarRocksLexer.CUME_DIST;
    static final int CUMULATIVE = StarRocksLexer.CUMULATIVE;
    static final int CURRENT = StarRocksLexer.CURRENT;
    static final int CURRENT_DATE = StarRocksLexer.CURRENT_DATE;
    static final int CURRENT_GROUP = StarRocksLexer.CURRENT_GROUP;
    static final int CURRENT_WAREHOUSE = StarRocksLexer.CURRENT_WAREHOUSE;
    static final int CURRENT_ROLE = StarRocksLexer.CURRENT_ROLE;
    static final int CURRENT_TIME = StarRocksLexer.CURRENT_TIME;
    static final int CURRENT_TIMESTAMP = StarRocksLexer.CURRENT_TIMESTAMP;
    static final int CURRENT_USER = StarRocksLexer.CURRENT_USER;
    static final int DATA = StarRocksLexer.DATA;
    static final int DATACACHE = StarRocksLexer.DATACACHE;
    static final int DATABASE = StarRocksLexer.DATABASE;
    static final int DATABASES = StarRocksLexer.DATABASES;
    static final int DATE = StarRocksLexer.DATE;
    static final int DATETIME = StarRocksLexer.DATETIME;
    static final int DAY = StarRocksLexer.DAY;
    static final int DAYS = StarRocksLexer.DAYS;
    static final int DEALLOCATE = StarRocksLexer.DEALLOCATE;
    static final int DECIMAL = StarRocksLexer.DECIMAL;
    static final int DECIMALV2 = StarRocksLexer.DECIMALV2;
    static final int DECIMAL32 = StarRocksLexer.DECIMAL32;
    static final int DECIMAL64 = StarRocksLexer.DECIMAL64;
    static final int DECIMAL128 = StarRocksLexer.DECIMAL128;
    static final int DECIMAL256 = StarRocksLexer.DECIMAL256;
    static final int DECOMMISSION = StarRocksLexer.DECOMMISSION;
    static final int DEFAULT = StarRocksLexer.DEFAULT;
    static final int DELETE = StarRocksLexer.DELETE;
    static final int DENSE_RANK = StarRocksLexer.DENSE_RANK;
    static final int DEFERRED = StarRocksLexer.DEFERRED;
    static final int DIALECT = StarRocksLexer.DIALECT;
    static final int DICTIONARY = StarRocksLexer.DICTIONARY;
    static final int DICTIONARY_GET = StarRocksLexer.DICTIONARY_GET;
    static final int NTILE = StarRocksLexer.NTILE;
    static final int DIGEST = StarRocksLexer.DIGEST;
    static final int DESC = StarRocksLexer.DESC;
    static final int DESCRIBE = StarRocksLexer.DESCRIBE;
    static final int DISABLE = StarRocksLexer.DISABLE;
    static final int DISTINCT = StarRocksLexer.DISTINCT;
    static final int DISTRIBUTED = StarRocksLexer.DISTRIBUTED;
    static final int DISTRIBUTION = StarRocksLexer.DISTRIBUTION;
    static final int DOUBLE = StarRocksLexer.DOUBLE;
    static final int DROP = StarRocksLexer.DROP;
    static final int DUAL = StarRocksLexer.DUAL;
    static final int DUPLICATE = StarRocksLexer.DUPLICATE;
    static final int DYNAMIC = StarRocksLexer.DYNAMIC;
    static final int ELSE = StarRocksLexer.ELSE;
    static final int ENABLE = StarRocksLexer.ENABLE;
    static final int ENCLOSE = StarRocksLexer.ENCLOSE;
    static final int END = StarRocksLexer.END;
    static final int ENGINE = StarRocksLexer.ENGINE;
    static final int ENGINES = StarRocksLexer.ENGINES;
    static final int ERRORS = StarRocksLexer.ERRORS;
    static final int ESCAPE = StarRocksLexer.ESCAPE;
    static final int EVENTS = StarRocksLexer.EVENTS;
    static final int EXCEPT = StarRocksLexer.EXCEPT;
    static final int EXCLUDE = StarRocksLexer.EXCLUDE;
    static final int EXECUTE = StarRocksLexer.EXECUTE;
    static final int EXISTS = StarRocksLexer.EXISTS;
    static final int EXPLAIN = StarRocksLexer.EXPLAIN;
    static final int EXPORT = StarRocksLexer.EXPORT;
    static final int EXTERNAL = StarRocksLexer.EXTERNAL;
    static final int EXTRACT = StarRocksLexer.EXTRACT;
    static final int EVERY = StarRocksLexer.EVERY;
    static final int FAILPOINT = StarRocksLexer.FAILPOINT;
    static final int FAILPOINTS = StarRocksLexer.FAILPOINTS;
    static final int FALSE = StarRocksLexer.FALSE;
    static final int FIELDS = StarRocksLexer.FIELDS;
    static final int FILE = StarRocksLexer.FILE;
    static final int FILES = StarRocksLexer.FILES;
    static final int FILTER = StarRocksLexer.FILTER;
    static final int FIRST = StarRocksLexer.FIRST;
    static final int FIRST_VALUE = StarRocksLexer.FIRST_VALUE;
    static final int FLOAT = StarRocksLexer.FLOAT;
    static final int FLOOR = StarRocksLexer.FLOOR;
    static final int FN = StarRocksLexer.FN;
    static final int FOLLOWING = StarRocksLexer.FOLLOWING;
    static final int FOLLOWER = StarRocksLexer.FOLLOWER;
    static final int FOR = StarRocksLexer.FOR;
    static final int FORCE = StarRocksLexer.FORCE;
    static final int FORMAT = StarRocksLexer.FORMAT;
    static final int FREE = StarRocksLexer.FREE;
    static final int FROM = StarRocksLexer.FROM;
    static final int FRONTEND = StarRocksLexer.FRONTEND;
    static final int FRONTENDS = StarRocksLexer.FRONTENDS;
    static final int FULL = StarRocksLexer.FULL;
    static final int FUNCTION = StarRocksLexer.FUNCTION;
    static final int FUNCTIONS = StarRocksLexer.FUNCTIONS;
    static final int GLOBAL = StarRocksLexer.GLOBAL;
    static final int GRANT = StarRocksLexer.GRANT;
    static final int GRANTS = StarRocksLexer.GRANTS;
    static final int GROUP = StarRocksLexer.GROUP;
    static final int GROUPS = StarRocksLexer.GROUPS;
    static final int GROUPING = StarRocksLexer.GROUPING;
    static final int GROUPING_ID = StarRocksLexer.GROUPING_ID;
    static final int GROUP_CONCAT = StarRocksLexer.GROUP_CONCAT;
    static final int HASH = StarRocksLexer.HASH;
    static final int HAVING = StarRocksLexer.HAVING;
    static final int HELP = StarRocksLexer.HELP;
    static final int HISTOGRAM = StarRocksLexer.HISTOGRAM;
    static final int HLL = StarRocksLexer.HLL;
    static final int HLL_UNION = StarRocksLexer.HLL_UNION;
    static final int HOST = StarRocksLexer.HOST;
    static final int HOUR = StarRocksLexer.HOUR;
    static final int HOURS = StarRocksLexer.HOURS;
    static final int HUB = StarRocksLexer.HUB;
    static final int IDENTIFIED = StarRocksLexer.IDENTIFIED;
    static final int IF = StarRocksLexer.IF;
    static final int IMPERSONATE = StarRocksLexer.IMPERSONATE;
    static final int IMMEDIATE = StarRocksLexer.IMMEDIATE;
    static final int IGNORE = StarRocksLexer.IGNORE;
    static final int IMAGE = StarRocksLexer.IMAGE;
    static final int IN = StarRocksLexer.IN;
    static final int INACTIVE = StarRocksLexer.INACTIVE;
    static final int INCLUDE = StarRocksLexer.INCLUDE;
    static final int INCREMENTAL = StarRocksLexer.INCREMENTAL;
    static final int INDEX = StarRocksLexer.INDEX;
    static final int INDEXES = StarRocksLexer.INDEXES;
    static final int INFILE = StarRocksLexer.INFILE;
    static final int INNER = StarRocksLexer.INNER;
    static final int INSTALL = StarRocksLexer.INSTALL;
    static final int INSERT = StarRocksLexer.INSERT;
    static final int INT = StarRocksLexer.INT;
    static final int INTEGER = StarRocksLexer.INTEGER;
    static final int INTEGRATION = StarRocksLexer.INTEGRATION;
    static final int INTEGRATIONS = StarRocksLexer.INTEGRATIONS;
    static final int INTERMEDIATE = StarRocksLexer.INTERMEDIATE;
    static final int INTERSECT = StarRocksLexer.INTERSECT;
    static final int INTERVAL = StarRocksLexer.INTERVAL;
    static final int INTO = StarRocksLexer.INTO;
    static final int INVOKER = StarRocksLexer.INVOKER;
    static final int GIN = StarRocksLexer.GIN;
    static final int OVERWRITE = StarRocksLexer.OVERWRITE;
    static final int IS = StarRocksLexer.IS;
    static final int ISOLATION = StarRocksLexer.ISOLATION;
    static final int JOB = StarRocksLexer.JOB;
    static final int JOIN = StarRocksLexer.JOIN;
    static final int JSON = StarRocksLexer.JSON;
    static final int KEY = StarRocksLexer.KEY;
    static final int KEYS = StarRocksLexer.KEYS;
    static final int KILL = StarRocksLexer.KILL;
    static final int LABEL = StarRocksLexer.LABEL;
    static final int LAG = StarRocksLexer.LAG;
    static final int LARGEINT = StarRocksLexer.LARGEINT;
    static final int LAST = StarRocksLexer.LAST;
    static final int LAST_VALUE = StarRocksLexer.LAST_VALUE;
    static final int LATERAL = StarRocksLexer.LATERAL;
    static final int LEAD = StarRocksLexer.LEAD;
    static final int LEFT = StarRocksLexer.LEFT;
    static final int LESS = StarRocksLexer.LESS;
    static final int LEVEL = StarRocksLexer.LEVEL;
    static final int LIKE = StarRocksLexer.LIKE;
    static final int LIMIT = StarRocksLexer.LIMIT;
    static final int LIST = StarRocksLexer.LIST;
    static final int LOAD = StarRocksLexer.LOAD;
    static final int LOCAL = StarRocksLexer.LOCAL;
    static final int LOCALTIME = StarRocksLexer.LOCALTIME;
    static final int LOCALTIMESTAMP = StarRocksLexer.LOCALTIMESTAMP;
    static final int LOCATION = StarRocksLexer.LOCATION;
    static final int LOCATIONS = StarRocksLexer.LOCATIONS;
    static final int LOGS = StarRocksLexer.LOGS;
    static final int LOGICAL = StarRocksLexer.LOGICAL;
    static final int MANUAL = StarRocksLexer.MANUAL;
    static final int MAP = StarRocksLexer.MAP;
    static final int MAPPING = StarRocksLexer.MAPPING;
    static final int MAPPINGS = StarRocksLexer.MAPPINGS;
    static final int MASKING = StarRocksLexer.MASKING;
    static final int MATCH = StarRocksLexer.MATCH;
    static final int MATCH_ANY = StarRocksLexer.MATCH_ANY;
    static final int MATCH_ALL = StarRocksLexer.MATCH_ALL;
    static final int MATERIALIZED = StarRocksLexer.MATERIALIZED;
    static final int MAX = StarRocksLexer.MAX;
    static final int MAXVALUE = StarRocksLexer.MAXVALUE;
    static final int MERGE = StarRocksLexer.MERGE;
    static final int MICROSECOND = StarRocksLexer.MICROSECOND;
    static final int MILLISECOND = StarRocksLexer.MILLISECOND;
    static final int MIN = StarRocksLexer.MIN;
    static final int MINUTE = StarRocksLexer.MINUTE;
    static final int MINUTES = StarRocksLexer.MINUTES;
    static final int MINUS = StarRocksLexer.MINUS;
    static final int META = StarRocksLexer.META;
    static final int METADATA = StarRocksLexer.METADATA;
    static final int MOD = StarRocksLexer.MOD;
    static final int MODE = StarRocksLexer.MODE;
    static final int MODIFY = StarRocksLexer.MODIFY;
    static final int MONTH = StarRocksLexer.MONTH;
    static final int MULTIPLE = StarRocksLexer.MULTIPLE;
    static final int NAME = StarRocksLexer.NAME;
    static final int NAMES = StarRocksLexer.NAMES;
    static final int NEGATIVE = StarRocksLexer.NEGATIVE;
    static final int NGRAMBF = StarRocksLexer.NGRAMBF;
    static final int NO = StarRocksLexer.NO;
    static final int NODE = StarRocksLexer.NODE;
    static final int NODES = StarRocksLexer.NODES;
    static final int NONE = StarRocksLexer.NONE;
    static final int NOT = StarRocksLexer.NOT;
    static final int NULL = StarRocksLexer.NULL;
    static final int NULLS = StarRocksLexer.NULLS;
    static final int NUMBER = StarRocksLexer.NUMBER;
    static final int NUMERIC = StarRocksLexer.NUMERIC;
    static final int OBSERVER = StarRocksLexer.OBSERVER;
    static final int OF = StarRocksLexer.OF;
    static final int OFF = StarRocksLexer.OFF;
    static final int OFFSET = StarRocksLexer.OFFSET;
    static final int ON = StarRocksLexer.ON;
    static final int ONLY = StarRocksLexer.ONLY;
    static final int OPEN = StarRocksLexer.OPEN;
    static final int OPERATE = StarRocksLexer.OPERATE;
    static final int OPTIMIZE = StarRocksLexer.OPTIMIZE;
    static final int OPTIMIZER = StarRocksLexer.OPTIMIZER;
    static final int OPTION = StarRocksLexer.OPTION;
    static final int OR = StarRocksLexer.OR;
    static final int ORDER = StarRocksLexer.ORDER;
    static final int OUTER = StarRocksLexer.OUTER;
    static final int OUTFILE = StarRocksLexer.OUTFILE;
    static final int OVER = StarRocksLexer.OVER;
    static final int PARAMETER = StarRocksLexer.PARAMETER;
    static final int PARTITION = StarRocksLexer.PARTITION;
    static final int PARTITIONS = StarRocksLexer.PARTITIONS;
    static final int PASSWORD = StarRocksLexer.PASSWORD;
    static final int PATH = StarRocksLexer.PATH;
    static final int PAUSE = StarRocksLexer.PAUSE;
    static final int PENDING = StarRocksLexer.PENDING;
    static final int PERCENT_RANK = StarRocksLexer.PERCENT_RANK;
    static final int PERCENTILE = StarRocksLexer.PERCENTILE;
    static final int PERCENTILE_UNION = StarRocksLexer.PERCENTILE_UNION;
    static final int PLAN = StarRocksLexer.PLAN;
    static final int PLUGIN = StarRocksLexer.PLUGIN;
    static final int PLUGINS = StarRocksLexer.PLUGINS;
    static final int PIPE = StarRocksLexer.PIPE;
    static final int PIPES = StarRocksLexer.PIPES;
    static final int PIVOT = StarRocksLexer.PIVOT;
    static final int POLICY = StarRocksLexer.POLICY;
    static final int POLICIES = StarRocksLexer.POLICIES;
    static final int PRECEDING = StarRocksLexer.PRECEDING;
    static final int PREDICATE = StarRocksLexer.PREDICATE;
    static final int PREPARE = StarRocksLexer.PREPARE;
    static final int PRIMARY = StarRocksLexer.PRIMARY;
    static final int PRIORITY = StarRocksLexer.PRIORITY;
    static final int PRIVILEGES = StarRocksLexer.PRIVILEGES;
    static final int PROBABILITY = StarRocksLexer.PROBABILITY;
    static final int PROC = StarRocksLexer.PROC;
    static final int PROCEDURE = StarRocksLexer.PROCEDURE;
    static final int PROCESSLIST = StarRocksLexer.PROCESSLIST;
    static final int PROFILE = StarRocksLexer.PROFILE;
    static final int PROFILELIST = StarRocksLexer.PROFILELIST;
    static final int PROPERTIES = StarRocksLexer.PROPERTIES;
    static final int PROPERTY = StarRocksLexer.PROPERTY;
    static final int PROVIDER = StarRocksLexer.PROVIDER;
    static final int PROVIDERS = StarRocksLexer.PROVIDERS;
    static final int QUALIFY = StarRocksLexer.QUALIFY;
    static final int QUARTER = StarRocksLexer.QUARTER;
    static final int QUERY = StarRocksLexer.QUERY;
    static final int QUERIES = StarRocksLexer.QUERIES;
    static final int QUEUE = StarRocksLexer.QUEUE;
    static final int QUOTA = StarRocksLexer.QUOTA;
    static final int RANDOM = StarRocksLexer.RANDOM;
    static final int RANGE = StarRocksLexer.RANGE;
    static final int RANK = StarRocksLexer.RANK;
    static final int READ = StarRocksLexer.READ;
    static final int REASON = StarRocksLexer.REASON;
    static final int RECURSIVE = StarRocksLexer.RECURSIVE;
    static final int RECOVER = StarRocksLexer.RECOVER;
    static final int REFRESH = StarRocksLexer.REFRESH;
    static final int REWRITE = StarRocksLexer.REWRITE;
    static final int REGEXP = StarRocksLexer.REGEXP;
    static final int RELEASE = StarRocksLexer.RELEASE;
    static final int REMOVE = StarRocksLexer.REMOVE;
    static final int RENAME = StarRocksLexer.RENAME;
    static final int REPAIR = StarRocksLexer.REPAIR;
    static final int REPEATABLE = StarRocksLexer.REPEATABLE;
    static final int REPLACE = StarRocksLexer.REPLACE;
    static final int REPLACE_IF_NOT_NULL = StarRocksLexer.REPLACE_IF_NOT_NULL;
    static final int REPLICA = StarRocksLexer.REPLICA;
    static final int REPOSITORY = StarRocksLexer.REPOSITORY;
    static final int REPOSITORIES = StarRocksLexer.REPOSITORIES;
    static final int RESOURCE = StarRocksLexer.RESOURCE;
    static final int RESOURCES = StarRocksLexer.RESOURCES;
    static final int RESTORE = StarRocksLexer.RESTORE;
    static final int RESUME = StarRocksLexer.RESUME;
    static final int RETAIN = StarRocksLexer.RETAIN;
    static final int RETENTION = StarRocksLexer.RETENTION;
    static final int RETURNS = StarRocksLexer.RETURNS;
    static final int RETRY = StarRocksLexer.RETRY;
    static final int REVOKE = StarRocksLexer.REVOKE;
    static final int REVERT = StarRocksLexer.REVERT;
    static final int RIGHT = StarRocksLexer.RIGHT;
    static final int RLIKE = StarRocksLexer.RLIKE;
    static final int ROLE = StarRocksLexer.ROLE;
    static final int ROLES = StarRocksLexer.ROLES;
    static final int ROLLBACK = StarRocksLexer.ROLLBACK;
    static final int ROLLUP = StarRocksLexer.ROLLUP;
    static final int ROUTINE = StarRocksLexer.ROUTINE;
    static final int ROW = StarRocksLexer.ROW;
    static final int ROWS = StarRocksLexer.ROWS;
    static final int ROW_NUMBER = StarRocksLexer.ROW_NUMBER;
    static final int RULE = StarRocksLexer.RULE;
    static final int RULES = StarRocksLexer.RULES;
    static final int RUNNING = StarRocksLexer.RUNNING;
    static final int SAMPLE = StarRocksLexer.SAMPLE;
    static final int SCHEDULE = StarRocksLexer.SCHEDULE;
    static final int SCHEDULER = StarRocksLexer.SCHEDULER;
    static final int SCHEMA = StarRocksLexer.SCHEMA;
    static final int SCHEMAS = StarRocksLexer.SCHEMAS;
    static final int SECOND = StarRocksLexer.SECOND;
    static final int SECURITY = StarRocksLexer.SECURITY;
    static final int SELECT = StarRocksLexer.SELECT;
    static final int SEMI = StarRocksLexer.SEMI;
    static final int SEPARATOR = StarRocksLexer.SEPARATOR;
    static final int SERIALIZABLE = StarRocksLexer.SERIALIZABLE;
    static final int SESSION = StarRocksLexer.SESSION;
    static final int SET = StarRocksLexer.SET;
    static final int SETS = StarRocksLexer.SETS;
    static final int SET_VAR = StarRocksLexer.SET_VAR;
    static final int SIGNED = StarRocksLexer.SIGNED;
    static final int SKIP_KW = StarRocksLexer.SKIP_KW;
    static final int SKIP_HEADER = StarRocksLexer.SKIP_HEADER;
    static final int SHOW = StarRocksLexer.SHOW;
    static final int SMALLINT = StarRocksLexer.SMALLINT;
    static final int SNAPSHOT = StarRocksLexer.SNAPSHOT;
    static final int SNAPSHOTS = StarRocksLexer.SNAPSHOTS;
    static final int SPLIT = StarRocksLexer.SPLIT;
    static final int SQL = StarRocksLexer.SQL;
    static final int SQLBLACKLIST = StarRocksLexer.SQLBLACKLIST;
    static final int STARROCKS = StarRocksLexer.STARROCKS;
    static final int START = StarRocksLexer.START;
    static final int STATS = StarRocksLexer.STATS;
    static final int STATUS = StarRocksLexer.STATUS;
    static final int STOP = StarRocksLexer.STOP;
    static final int STORAGE = StarRocksLexer.STORAGE;
    static final int STREAM = StarRocksLexer.STREAM;
    static final int STRING = StarRocksLexer.STRING;
    static final int TEXT = StarRocksLexer.TEXT;
    static final int SUBMIT = StarRocksLexer.SUBMIT;
    static final int SUM = StarRocksLexer.SUM;
    static final int SUSPEND = StarRocksLexer.SUSPEND;
    static final int SYNC = StarRocksLexer.SYNC;
    static final int SYSTEM = StarRocksLexer.SYSTEM;
    static final int SYSTEM_TIME = StarRocksLexer.SYSTEM_TIME;
    static final int SWAP = StarRocksLexer.SWAP;
    static final int STRUCT = StarRocksLexer.STRUCT;
    static final int TABLE = StarRocksLexer.TABLE;
    static final int TABLES = StarRocksLexer.TABLES;
    static final int TABLET = StarRocksLexer.TABLET;
    static final int TABLETS = StarRocksLexer.TABLETS;
    static final int TAG = StarRocksLexer.TAG;
    static final int TASK = StarRocksLexer.TASK;
    static final int TEMPORARY = StarRocksLexer.TEMPORARY;
    static final int TERMINATED = StarRocksLexer.TERMINATED;
    static final int THAN = StarRocksLexer.THAN;
    static final int THEN = StarRocksLexer.THEN;
    static final int TIME = StarRocksLexer.TIME;
    static final int TIMES = StarRocksLexer.TIMES;
    static final int TIMESTAMP = StarRocksLexer.TIMESTAMP;
    static final int TIMESTAMPADD = StarRocksLexer.TIMESTAMPADD;
    static final int TIMESTAMPDIFF = StarRocksLexer.TIMESTAMPDIFF;
    static final int TINYINT = StarRocksLexer.TINYINT;
    static final int TRANSACTION = StarRocksLexer.TRANSACTION;
    static final int TRANSLATE = StarRocksLexer.TRANSLATE;
    static final int TO = StarRocksLexer.TO;
    static final int TRACE = StarRocksLexer.TRACE;
    static final int TRIGGERS = StarRocksLexer.TRIGGERS;
    static final int TRIM_SPACE = StarRocksLexer.TRIM_SPACE;
    static final int TRUE = StarRocksLexer.TRUE;
    static final int TRUNCATE = StarRocksLexer.TRUNCATE;
    static final int TYPE = StarRocksLexer.TYPE;
    static final int TYPES = StarRocksLexer.TYPES;
    static final int UNBOUNDED = StarRocksLexer.UNBOUNDED;
    static final int UNCOMMITTED = StarRocksLexer.UNCOMMITTED;
    static final int UNION = StarRocksLexer.UNION;
    static final int UNIQUE = StarRocksLexer.UNIQUE;
    static final int UNINSTALL = StarRocksLexer.UNINSTALL;
    static final int UNSET = StarRocksLexer.UNSET;
    static final int UNSIGNED = StarRocksLexer.UNSIGNED;
    static final int UPDATE = StarRocksLexer.UPDATE;
    static final int USAGE = StarRocksLexer.USAGE;
    static final int USE = StarRocksLexer.USE;
    static final int USER = StarRocksLexer.USER;
    static final int USERS = StarRocksLexer.USERS;
    static final int USING = StarRocksLexer.USING;
    static final int VALUE = StarRocksLexer.VALUE;
    static final int VALUES = StarRocksLexer.VALUES;
    static final int VARBINARY = StarRocksLexer.VARBINARY;
    static final int VARCHAR = StarRocksLexer.VARCHAR;
    static final int VARIABLES = StarRocksLexer.VARIABLES;
    static final int VARIANT = StarRocksLexer.VARIANT;
    static final int VECTOR = StarRocksLexer.VECTOR;
    static final int VERBOSE = StarRocksLexer.VERBOSE;
    static final int VERSION = StarRocksLexer.VERSION;
    static final int VIEW = StarRocksLexer.VIEW;
    static final int VIEWS = StarRocksLexer.VIEWS;
    static final int VOLUME = StarRocksLexer.VOLUME;
    static final int VOLUMES = StarRocksLexer.VOLUMES;
    static final int WAREHOUSE = StarRocksLexer.WAREHOUSE;
    static final int WAREHOUSES = StarRocksLexer.WAREHOUSES;
    static final int WARNINGS = StarRocksLexer.WARNINGS;
    static final int WEEK = StarRocksLexer.WEEK;
    static final int WHEN = StarRocksLexer.WHEN;
    static final int WHERE = StarRocksLexer.WHERE;
    static final int WHITELIST = StarRocksLexer.WHITELIST;
    static final int WITH = StarRocksLexer.WITH;
    static final int WORK = StarRocksLexer.WORK;
    static final int WRITE = StarRocksLexer.WRITE;
    static final int YEAR = StarRocksLexer.YEAR;
    static final int LOCK = StarRocksLexer.LOCK;
    static final int UNLOCK = StarRocksLexer.UNLOCK;
    static final int LOW_PRIORITY = StarRocksLexer.LOW_PRIORITY;
    static final int DISK = StarRocksLexer.DISK;
    static final int BEFORE = StarRocksLexer.BEFORE;
    static final int DOUBLE_DOLLAR = StarRocksLexer.DOUBLE_DOLLAR;
    static final int FIELD = StarRocksLexer.FIELD;
    static final int PERSISTENT = StarRocksLexer.PERSISTENT;
    static final int EQ = StarRocksLexer.EQ;
    static final int NEQ = StarRocksLexer.NEQ;
    static final int LT = StarRocksLexer.LT;
    static final int LTE = StarRocksLexer.LTE;
    static final int GT = StarRocksLexer.GT;
    static final int GTE = StarRocksLexer.GTE;
    static final int EQ_FOR_NULL = StarRocksLexer.EQ_FOR_NULL;
    static final int ARRAY_ELEMENT = StarRocksLexer.ARRAY_ELEMENT;
    static final int PLUS_SYMBOL = StarRocksLexer.PLUS_SYMBOL;
    static final int MINUS_SYMBOL = StarRocksLexer.MINUS_SYMBOL;
    static final int ASTERISK_SYMBOL = StarRocksLexer.ASTERISK_SYMBOL;
    static final int SLASH_SYMBOL = StarRocksLexer.SLASH_SYMBOL;
    static final int PERCENT_SYMBOL = StarRocksLexer.PERCENT_SYMBOL;
    static final int LOGICAL_OR = StarRocksLexer.LOGICAL_OR;
    static final int LOGICAL_AND = StarRocksLexer.LOGICAL_AND;
    static final int LOGICAL_NOT = StarRocksLexer.LOGICAL_NOT;
    static final int INT_DIV = StarRocksLexer.INT_DIV;
    static final int BITAND = StarRocksLexer.BITAND;
    static final int BITOR = StarRocksLexer.BITOR;
    static final int BITXOR = StarRocksLexer.BITXOR;
    static final int BITNOT = StarRocksLexer.BITNOT;
    static final int BIT_SHIFT_LEFT = StarRocksLexer.BIT_SHIFT_LEFT;
    static final int BIT_SHIFT_RIGHT = StarRocksLexer.BIT_SHIFT_RIGHT;
    static final int BIT_SHIFT_RIGHT_LOGICAL = StarRocksLexer.BIT_SHIFT_RIGHT_LOGICAL;
    static final int ARROW = StarRocksLexer.ARROW;
    static final int AT = StarRocksLexer.AT;
    static final int INTEGER_VALUE = StarRocksLexer.INTEGER_VALUE;
    static final int DECIMAL_VALUE = StarRocksLexer.DECIMAL_VALUE;
    static final int DOUBLE_VALUE = StarRocksLexer.DOUBLE_VALUE;
    static final int SINGLE_QUOTED_TEXT = StarRocksLexer.SINGLE_QUOTED_TEXT;
    static final int DOUBLE_QUOTED_TEXT = StarRocksLexer.DOUBLE_QUOTED_TEXT;
    static final int BINARY_SINGLE_QUOTED_TEXT = StarRocksLexer.BINARY_SINGLE_QUOTED_TEXT;
    static final int BINARY_DOUBLE_QUOTED_TEXT = StarRocksLexer.BINARY_DOUBLE_QUOTED_TEXT;
    static final int LETTER_IDENTIFIER = StarRocksLexer.LETTER_IDENTIFIER;
    static final int DIGIT_IDENTIFIER = StarRocksLexer.DIGIT_IDENTIFIER;
    static final int BACKQUOTED_IDENTIFIER = StarRocksLexer.BACKQUOTED_IDENTIFIER;
    static final int DOT_IDENTIFIER = StarRocksLexer.DOT_IDENTIFIER;
    static final int SIMPLE_COMMENT = StarRocksLexer.SIMPLE_COMMENT;
    static final int BRACKETED_COMMENT = StarRocksLexer.BRACKETED_COMMENT;
    static final int OPTIMIZER_HINT = StarRocksLexer.OPTIMIZER_HINT;
    static final int SEMICOLON = StarRocksLexer.SEMICOLON;
    static final int DOTDOTDOT = StarRocksLexer.DOTDOTDOT;
    static final int WS = StarRocksLexer.WS;
    static final int ATTACHMENT = StarRocksLexer.ATTACHMENT;
    static final int CONCAT = StarRocksParser.CONCAT;
    // Token type of '.'.
    static final int DOT_TYPE = StarRocksLexer.T__1;

    // UnifiedBatchedLexer reads these operators with its own code because they can also start a comment,
    // a number or a token that depends on the SQL mode, so the operator trie leaves them out.
    private static final java.util.Set<String> OPERATORS_OUTSIDE_TRIE =
            java.util.Set.of("$$", "-", "->", ".", "...", "/", "|", "||");
    // Keyword trie symbols: letters a-z, digits, '_' and '$', as UnifiedBatchedLexer.symbol() maps them.
    private static final int KEYWORD_SYMBOLS = 38;

    // Tries of literal tokens. Node 0 has no edges, node 1 is the root, and the types array holds the token
    // type that ends at a node or 0.
    static final int[][] LITERAL_EDGES;
    static final int[] LITERAL_TYPES;
    static final int[][] KEYWORD_EDGES;
    static final int[] KEYWORD_TYPES;

    static {
        java.util.List<int[]> literalEdges = new java.util.ArrayList<>();
        java.util.List<Integer> literalTypes = new java.util.ArrayList<>();
        java.util.List<int[]> keywordEdges = new java.util.ArrayList<>();
        java.util.List<Integer> keywordTypes = new java.util.ArrayList<>();
        for (int i = 0; i < 2; i++) {
            literalEdges.add(new int[128]);
            literalTypes.add(0);
            keywordEdges.add(new int[KEYWORD_SYMBOLS]);
            keywordTypes.add(0);
        }
        org.antlr.v4.runtime.Vocabulary vocabulary = StarRocksLexer.VOCABULARY;
        for (int type = 1; type <= vocabulary.getMaxTokenType(); type++) {
            String name = vocabulary.getLiteralName(type);
            if (name == null) {
                continue;
            }
            String text = name.substring(1, name.length() - 1);
            if (isWord(text)) {
                insert(keywordEdges, keywordTypes, text, type, true);
            } else if (!OPERATORS_OUTSIDE_TRIE.contains(text)) {
                insert(literalEdges, literalTypes, text, type, false);
            }
        }
        // NEQ is '<>' | '!=', so the vocabulary has no single literal for it.
        insert(literalEdges, literalTypes, "<>", StarRocksLexer.NEQ, false);
        insert(literalEdges, literalTypes, "!=", StarRocksLexer.NEQ, false);
        LITERAL_EDGES = literalEdges.toArray(new int[0][]);
        LITERAL_TYPES = literalTypes.stream().mapToInt(Integer::intValue).toArray();
        KEYWORD_EDGES = keywordEdges.toArray(new int[0][]);
        KEYWORD_TYPES = keywordTypes.stream().mapToInt(Integer::intValue).toArray();
    }

    private static boolean isWord(String text) {
        char first = text.charAt(0);
        return first >= 'A' && first <= 'Z' || first == '_';
    }

    private static int keywordSymbol(char c) {
        if (c >= 'A' && c <= 'Z') {
            return c - 'A';
        }
        if (c >= '0' && c <= '9') {
            return 26 + c - '0';
        }
        return c == '_' ? 36 : 37;
    }

    private static void insert(java.util.List<int[]> edges, java.util.List<Integer> types, String text, int type,
                               boolean keyword) {
        int node = 1;
        for (int i = 0; i < text.length(); i++) {
            int symbol = keyword ? keywordSymbol(text.charAt(i)) : text.charAt(i);
            int next = edges.get(node)[symbol];
            if (next == 0) {
                next = edges.size();
                edges.add(new int[keyword ? KEYWORD_SYMBOLS : 128]);
                types.add(0);
                edges.get(node)[symbol] = next;
            }
            node = next;
        }
        types.set(node, type);
    }
}
